### PR TITLE
Performance fixes

### LINKED ISSUE #65: Slow typing performance on long emails
While testing the last few pull requests, I've noticed that typing into long emails is very laggy.  I profiled the code and found that the checkForWarnings function in just-not-sorry is the culprit.  It adds and removes the warnings each time you type a character.  This causes Chrome to recalculate the layout of the DOM over and over again, which is slow when there are a lot of nodes being impacted.  We should implement a less expensive method of handling warnings to address this issue.  The changes needed to fix this issue could also serve as a base for being able to implement #59 .
just-not-sorry-profile

### PR DESCRIPTION
**Pull request by sbrudz**
This PR addresses performance issues with Just Not Sorry on long emails.  

In version 1.6.2 (and earlier), a long email with many just's and sorry's will slow typing performance to a crawl.  As noted in #65 this is because on each keystroke, the code is removing and re-adding all of the warnings.  This causes layout thrashing and greatly reduces performance as the browser tries to catch up.

This PR makes the following changes to improve performance:

* Reduce the frequency of calls to recalculate warnings by using a debounce function to only trigger the recalculation 0.5 seconds after typing stops.
* Batch DOM measurements and mutations to reduce layout thrashing using the [fastdom library](https://github.com/wilsonpage/fastdom)
* Eliminate extraneous input events by tightening up the mutation observer logic

It also adds more test coverage for the mutation observer-related code.

Fixes #65

### CODE REVIEW

File: spec/JustNotSorrySpec.js [hunk 1]
```diff
@@ -91,4 +147,99 @@ describe('JustNotSorry', function () {
...
+        dispatchEventOnElement(target, 'focus');
+        expect(warningChecker.addWarnings).toHaveBeenCalledTimes(1);
+        warningChecker.addWarnings.calls.reset();
+
+        setTimeout(function () {
+          let element = document.createElement('SPAN');
+          element.textContent = 'Hello';
+          target.appendChild(element);
+
+          setTimeout(function () {
```
Comment (mnunemacher-dm) [inline spec/JustNotSorrySpec.js:179]: These nested timeouts look like they must have been a pain to work with, but the tests all pass

Comment (sbrudz) [reply spec/JustNotSorrySpec.js:179]: They were definitely a pain.  I tried using jasmine's mock clock instead, but it didn't work.  From what I could tell from stack overflow posts, jasmine doesn't mock out enough to be able to trigger the mutation observers. setTimeout was the best I could do.  I'm open to suggestions for better ways to do it.  I'm also hoping that if we convert to jest, we'll be able to rewrite these tests to get rid of the setTimeouts.
